#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input().strip())

for _ in range(3, 100):
    if n >= 2 and n < 5 and n % 2 == 0:
        print("Not Weird")
        break
    elif n >= 6 and n < 20:
        print("Weird")
        break
    elif n % 2 == 0 and n > 20:
        print("Not Weird")
        break
    else:
        print("Weird")
        break

